name: dart_web_gpu
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.0-65.0.dev

dependencies:
  vector_math: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
